#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QrMgr
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qrmgr")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertqrcode(qrcode instance);
    partial void Updateqrcode(qrcode instance);
    partial void Deleteqrcode(qrcode instance);
    partial void Insertuploadlinq(uploadlinq instance);
    partial void Updateuploadlinq(uploadlinq instance);
    partial void Deleteuploadlinq(uploadlinq instance);
    partial void Inserttbluser(tbluser instance);
    partial void Updatetbluser(tbluser instance);
    partial void Deletetbluser(tbluser instance);
    partial void Insertbook(book instance);
    partial void Updatebook(book instance);
    partial void Deletebook(book instance);
    partial void Insertposition(position instance);
    partial void Updateposition(position instance);
    partial void Deleteposition(position instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["qrmgrConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<qrcode> qrcode
		{
			get
			{
				return this.GetTable<qrcode>();
			}
		}
		
		public System.Data.Linq.Table<uploadlinq> uploadlinq
		{
			get
			{
				return this.GetTable<uploadlinq>();
			}
		}
		
		public System.Data.Linq.Table<tbluser> tbluser
		{
			get
			{
				return this.GetTable<tbluser>();
			}
		}
		
		public System.Data.Linq.Table<book> book
		{
			get
			{
				return this.GetTable<book>();
			}
		}
		
		public System.Data.Linq.Table<position> position
		{
			get
			{
				return this.GetTable<position>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.qrcode")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class qrcode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _qrId;
		
		private System.Nullable<int> _uploadId;
		
		private string _Url;
		
		private System.Nullable<System.DateTime> _生成时间;
		
		private string _备注;
		
		private EntityRef<uploadlinq> _uploadlinq;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnqrIdChanging(int value);
    partial void OnqrIdChanged();
    partial void OnuploadIdChanging(System.Nullable<int> value);
    partial void OnuploadIdChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void On生成时间Changing(System.Nullable<System.DateTime> value);
    partial void On生成时间Changed();
    partial void On备注Changing(string value);
    partial void On备注Changed();
    #endregion
		
		public qrcode()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qrId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int qrId
		{
			get
			{
				return this._qrId;
			}
			set
			{
				if ((this._qrId != value))
				{
					this.OnqrIdChanging(value);
					this.SendPropertyChanging();
					this._qrId = value;
					this.SendPropertyChanged("qrId");
					this.OnqrIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uploadId", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<int> uploadId
		{
			get
			{
				return this._uploadId;
			}
			set
			{
				if ((this._uploadId != value))
				{
					if (this._uploadlinq.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuploadIdChanging(value);
					this.SendPropertyChanging();
					this._uploadId = value;
					this.SendPropertyChanged("uploadId");
					this.OnuploadIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_生成时间", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<System.DateTime> 生成时间
		{
			get
			{
				return this._生成时间;
			}
			set
			{
				if ((this._生成时间 != value))
				{
					this.On生成时间Changing(value);
					this.SendPropertyChanging();
					this._生成时间 = value;
					this.SendPropertyChanged("生成时间");
					this.On生成时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_备注", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string 备注
		{
			get
			{
				return this._备注;
			}
			set
			{
				if ((this._备注 != value))
				{
					this.On备注Changing(value);
					this.SendPropertyChanging();
					this._备注 = value;
					this.SendPropertyChanged("备注");
					this.On备注Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="uploadlinq_qrcode", Storage="_uploadlinq", ThisKey="uploadId", OtherKey="uploadId", IsForeignKey=true)]
		public uploadlinq uploadlinq
		{
			get
			{
				return this._uploadlinq.Entity;
			}
			set
			{
				uploadlinq previousValue = this._uploadlinq.Entity;
				if (((previousValue != value) 
							|| (this._uploadlinq.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._uploadlinq.Entity = null;
						previousValue.qrcode.Remove(this);
					}
					this._uploadlinq.Entity = value;
					if ((value != null))
					{
						value.qrcode.Add(this);
						this._uploadId = value.uploadId;
					}
					else
					{
						this._uploadId = default(Nullable<int>);
					}
					this.SendPropertyChanged("uploadlinq");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._uploadlinq = default(EntityRef<uploadlinq>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.upload")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class uploadlinq : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uploadId;
		
		private string _类型;
		
		private string _路径;
		
		private System.Nullable<System.DateTime> _上传时间;
		
		private string _备注;
		
		private System.Nullable<int> _是否启用;
		
		private EntitySet<qrcode> _qrcode;
		
		private bool serializing;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuploadIdChanging(int value);
    partial void OnuploadIdChanged();
    partial void On类型Changing(string value);
    partial void On类型Changed();
    partial void On路径Changing(string value);
    partial void On路径Changed();
    partial void On上传时间Changing(System.Nullable<System.DateTime> value);
    partial void On上传时间Changed();
    partial void On备注Changing(string value);
    partial void On备注Changed();
    partial void On是否启用Changing(System.Nullable<int> value);
    partial void On是否启用Changed();
    #endregion
		
		public uploadlinq()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uploadId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int uploadId
		{
			get
			{
				return this._uploadId;
			}
			set
			{
				if ((this._uploadId != value))
				{
					this.OnuploadIdChanging(value);
					this.SendPropertyChanging();
					this._uploadId = value;
					this.SendPropertyChanged("uploadId");
					this.OnuploadIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_类型", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string 类型
		{
			get
			{
				return this._类型;
			}
			set
			{
				if ((this._类型 != value))
				{
					this.On类型Changing(value);
					this.SendPropertyChanging();
					this._类型 = value;
					this.SendPropertyChanged("类型");
					this.On类型Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_路径", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string 路径
		{
			get
			{
				return this._路径;
			}
			set
			{
				if ((this._路径 != value))
				{
					this.On路径Changing(value);
					this.SendPropertyChanging();
					this._路径 = value;
					this.SendPropertyChanged("路径");
					this.On路径Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_上传时间", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<System.DateTime> 上传时间
		{
			get
			{
				return this._上传时间;
			}
			set
			{
				if ((this._上传时间 != value))
				{
					this.On上传时间Changing(value);
					this.SendPropertyChanging();
					this._上传时间 = value;
					this.SendPropertyChanged("上传时间");
					this.On上传时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_备注", DbType="VarChar(1024)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string 备注
		{
			get
			{
				return this._备注;
			}
			set
			{
				if ((this._备注 != value))
				{
					this.On备注Changing(value);
					this.SendPropertyChanging();
					this._备注 = value;
					this.SendPropertyChanged("备注");
					this.On备注Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_是否启用", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<int> 是否启用
		{
			get
			{
				return this._是否启用;
			}
			set
			{
				if ((this._是否启用 != value))
				{
					this.On是否启用Changing(value);
					this.SendPropertyChanging();
					this._是否启用 = value;
					this.SendPropertyChanged("是否启用");
					this.On是否启用Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="uploadlinq_qrcode", Storage="_qrcode", ThisKey="uploadId", OtherKey="uploadId")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7, EmitDefaultValue=false)]
		public EntitySet<qrcode> qrcode
		{
			get
			{
				if ((this.serializing 
							&& (this._qrcode.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._qrcode;
			}
			set
			{
				this._qrcode.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_qrcode(qrcode entity)
		{
			this.SendPropertyChanging();
			entity.uploadlinq = this;
		}
		
		private void detach_qrcode(qrcode entity)
		{
			this.SendPropertyChanging();
			entity.uploadlinq = null;
		}
		
		private void Initialize()
		{
			this._qrcode = new EntitySet<qrcode>(new Action<qrcode>(this.attach_qrcode), new Action<qrcode>(this.detach_qrcode));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbluser")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class tbluser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _用户名;
		
		private string _密码;
		
		private System.Nullable<int> _userflag;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On用户名Changing(string value);
    partial void On用户名Changed();
    partial void On密码Changing(string value);
    partial void On密码Changed();
    partial void OnuserflagChanging(System.Nullable<int> value);
    partial void OnuserflagChanged();
    #endregion
		
		public tbluser()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_用户名", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string 用户名
		{
			get
			{
				return this._用户名;
			}
			set
			{
				if ((this._用户名 != value))
				{
					this.On用户名Changing(value);
					this.SendPropertyChanging();
					this._用户名 = value;
					this.SendPropertyChanged("用户名");
					this.On用户名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_密码", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string 密码
		{
			get
			{
				return this._密码;
			}
			set
			{
				if ((this._密码 != value))
				{
					this.On密码Changing(value);
					this.SendPropertyChanging();
					this._密码 = value;
					this.SendPropertyChanged("密码");
					this.On密码Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userflag", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> userflag
		{
			get
			{
				return this._userflag;
			}
			set
			{
				if ((this._userflag != value))
				{
					this.OnuserflagChanging(value);
					this.SendPropertyChanging();
					this._userflag = value;
					this.SendPropertyChanged("userflag");
					this.OnuserflagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.book")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class book : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Book_Title;
		
		private string _Book_ISBN;
		
		private string _Book_Author;
		
		private string _Book_Brief;
		
		private System.Nullable<System.DateTime> _Book_Date;
		
		private string _Book_coverpath;
		
		private System.Nullable<System.DateTime> _Book_addDate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBook_TitleChanging(string value);
    partial void OnBook_TitleChanged();
    partial void OnBook_ISBNChanging(string value);
    partial void OnBook_ISBNChanged();
    partial void OnBook_AuthorChanging(string value);
    partial void OnBook_AuthorChanged();
    partial void OnBook_BriefChanging(string value);
    partial void OnBook_BriefChanged();
    partial void OnBook_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnBook_DateChanged();
    partial void OnBook_coverpathChanging(string value);
    partial void OnBook_coverpathChanged();
    partial void OnBook_addDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBook_addDateChanged();
    #endregion
		
		public book()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Title", DbType="VarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Book_Title
		{
			get
			{
				return this._Book_Title;
			}
			set
			{
				if ((this._Book_Title != value))
				{
					this.OnBook_TitleChanging(value);
					this.SendPropertyChanging();
					this._Book_Title = value;
					this.SendPropertyChanged("Book_Title");
					this.OnBook_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_ISBN", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Book_ISBN
		{
			get
			{
				return this._Book_ISBN;
			}
			set
			{
				if ((this._Book_ISBN != value))
				{
					this.OnBook_ISBNChanging(value);
					this.SendPropertyChanging();
					this._Book_ISBN = value;
					this.SendPropertyChanged("Book_ISBN");
					this.OnBook_ISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Author", DbType="VarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Book_Author
		{
			get
			{
				return this._Book_Author;
			}
			set
			{
				if ((this._Book_Author != value))
				{
					this.OnBook_AuthorChanging(value);
					this.SendPropertyChanging();
					this._Book_Author = value;
					this.SendPropertyChanged("Book_Author");
					this.OnBook_AuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Brief", DbType="VarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string Book_Brief
		{
			get
			{
				return this._Book_Brief;
			}
			set
			{
				if ((this._Book_Brief != value))
				{
					this.OnBook_BriefChanging(value);
					this.SendPropertyChanging();
					this._Book_Brief = value;
					this.SendPropertyChanged("Book_Brief");
					this.OnBook_BriefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Date", DbType="Date")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<System.DateTime> Book_Date
		{
			get
			{
				return this._Book_Date;
			}
			set
			{
				if ((this._Book_Date != value))
				{
					this.OnBook_DateChanging(value);
					this.SendPropertyChanging();
					this._Book_Date = value;
					this.SendPropertyChanged("Book_Date");
					this.OnBook_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_coverpath", DbType="VarChar(1000)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string Book_coverpath
		{
			get
			{
				return this._Book_coverpath;
			}
			set
			{
				if ((this._Book_coverpath != value))
				{
					this.OnBook_coverpathChanging(value);
					this.SendPropertyChanging();
					this._Book_coverpath = value;
					this.SendPropertyChanged("Book_coverpath");
					this.OnBook_coverpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_addDate", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<System.DateTime> Book_addDate
		{
			get
			{
				return this._Book_addDate;
			}
			set
			{
				if ((this._Book_addDate != value))
				{
					this.OnBook_addDateChanging(value);
					this.SendPropertyChanging();
					this._Book_addDate = value;
					this.SendPropertyChanged("Book_addDate");
					this.OnBook_addDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.position")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class position : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Book_ISBN;
		
		private string _Pos;
		
		private long _Id;
		
		private System.Nullable<int> _seq;
		
		private System.Nullable<int> _qrid;
		
		private string _name;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBook_ISBNChanging(string value);
    partial void OnBook_ISBNChanged();
    partial void OnPosChanging(string value);
    partial void OnPosChanged();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnseqChanging(System.Nullable<int> value);
    partial void OnseqChanged();
    partial void OnqridChanging(System.Nullable<int> value);
    partial void OnqridChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public position()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_ISBN", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Book_ISBN
		{
			get
			{
				return this._Book_ISBN;
			}
			set
			{
				if ((this._Book_ISBN != value))
				{
					this.OnBook_ISBNChanging(value);
					this.SendPropertyChanging();
					this._Book_ISBN = value;
					this.SendPropertyChanged("Book_ISBN");
					this.OnBook_ISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pos", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Pos
		{
			get
			{
				return this._Pos;
			}
			set
			{
				if ((this._Pos != value))
				{
					this.OnPosChanging(value);
					this.SendPropertyChanging();
					this._Pos = value;
					this.SendPropertyChanged("Pos");
					this.OnPosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seq", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<int> seq
		{
			get
			{
				return this._seq;
			}
			set
			{
				if ((this._seq != value))
				{
					this.OnseqChanging(value);
					this.SendPropertyChanging();
					this._seq = value;
					this.SendPropertyChanged("seq");
					this.OnseqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qrid", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> qrid
		{
			get
			{
				return this._qrid;
			}
			set
			{
				if ((this._qrid != value))
				{
					this.OnqridChanging(value);
					this.SendPropertyChanging();
					this._qrid = value;
					this.SendPropertyChanged("qrid");
					this.OnqridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
